apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-auth-service-deployment
  labels:
    app: car-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-auth-service
  template:
    metadata:
      labels:
        app: car-auth-service
    spec:
      containers:
      - name: car-auth-service-container
        image: abtaj.azurecr.io/car-auth-service:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        env:
        - name: MONGO_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: car-care-secrets
              key: mongo-db-username
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: car-care-secrets
              key: mongo-db-password
        - name: MONGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: car-care-secrets
              key: mongo-db-name