# Use the official Python base image
FROM python:3.10-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY car_auth_service/requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . .

RUN pip install -e global_helpers
RUN pip install -e car_service_contracts

# Expose the port that the server will listen on
EXPOSE 80

# Start the Uvicorn server
CMD ["uvicorn", "car_auth_service:app", "--host", "0.0.0.0", "--port", "80"]