name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME_CAR_AUTH: car-auth-service
  IMAGE_NAME_CAR_SERVICES: car-services-manager

jobs:
  build:
    name: Build docker image and push to ACR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Log into registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_KEY }}

      - name: Build the Docker image - CarAuthService
        run: docker build src/python_packages/ --file src/python_packages/Dockerfile_CarAuthService --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME_CAR_AUTH }}:latest

      - name: Build the Docker image - CarServicesManager
        run: docker build src/python_packages/ --file src/python_packages/Dockerfile_CarServicesManager --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME_CAR_SERVICES }}:latest

      - name: Push docker image to ACR
        run: docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME_CAR_AUTH }}:latest

      - name: Push docker image to ACR
        run: docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME_CAR_SERVICES }}:latest
